#!/usr/bin/env python3
"""
Extracts base stats and types from a Gen 3 Emerald ROM into committed Java.

    python3 tools/extract-base-stats.py "path/to/emerald.gba"

The ROM is the user's own file and is never committed; what this produces is
numbers, which are facts. It writes src/main/java/dev/yoru/game/BaseStats.java,
which party placement needs: a Pokemon moved into the party has to carry the
stats the game itself would calculate for it, or it shows the wrong numbers
until its next level-up.

This used to be extract-battle-data.py and also wrote a move table for the
practice battle engine. That engine is gone (battles happen in the real game
now), so only the stats remain.

Nothing here hardcodes a ROM offset. The table is located by searching for a
signature whose contents are already known, then verified against landmark
totals, so a wrong offset fails loudly instead of producing plausible garbage.

Species above the Hoenn starters are stored in regional dex order, so the
species-to-National mapping is read out of the ROM's own table rather than
assumed. The widely repeated "internal = National + 25" rule returns
Breloom's stats for Gardevoir.
"""
import struct, sys, pathlib

TYPES = ["Normal","Fighting","Flying","Poison","Ground","Rock","Bug","Ghost","Steel","Mystery",
         "Fire","Water","Grass","Electric","Psychic","Ice","Dragon","Dark"]

# Independently checkable values. If the extraction drifts, these fail.
STAT_CHECKS = {
    1:("Bulbasaur",318), 6:("Charizard",534), 25:("Pikachu",300), 150:("Mewtwo",680),
    213:("Shuckle",505), 242:("Blissey",540), 252:("Treecko",310), 282:("Gardevoir",518),
    286:("Breloom",460), 348:("Armaldo",495), 376:("Metagross",600),
    384:("Rayquaza",680), 386:("Deoxys",600),
}

OUTPUT = pathlib.Path("src/main/java/dev/yoru/game/BaseStats.java")

def find_all(rom, sig):
    out, at = [], 0
    while True:
        i = rom.find(sig, at)
        if i < 0: return out
        out.append(i); at = i + 1

def find_base_stats(rom):
    """Bulbasaur, confirmed by Ivysaur sitting one 28-byte entry later."""
    bulbasaur = bytes([45,49,49,45,65,65,12,3])
    ivysaur   = bytes([60,62,63,60,80,80,12,3])
    for hit in find_all(rom, bulbasaur):
        if rom[hit+28:hit+36] == ivysaur:
            return hit - 28
    raise SystemExit("Could not find the base-stat table in this ROM.")

def find_dex_map(rom):
    """The species-to-National table: an identity run, confirmed by Treecko."""
    identity = b"".join(struct.pack("<H", n) for n in range(1, 21))
    for hit in find_all(rom, identity):
        if struct.unpack_from("<H", rom, hit + (277-1)*2)[0] == 252:
            return hit
    raise SystemExit("Could not find the species-to-National-dex table in this ROM.")

def main():
    if len(sys.argv) < 2:
        raise SystemExit(__doc__)
    rom = pathlib.Path(sys.argv[1]).read_bytes()
    stats_at, dex_at = find_base_stats(rom), find_dex_map(rom)
    print("base stats  %s\nspecies-dex %s" % (hex(stats_at), hex(dex_at)))

    national_of = lambda sp: struct.unpack_from("<H", rom, dex_at + (sp-1)*2)[0]
    species_of = {}
    for sp in range(1, 412):
        n = national_of(sp)
        if 1 <= n <= 386 and n not in species_of:
            species_of[n] = sp
    missing = [n for n in range(1, 387) if n not in species_of]
    if missing:
        raise SystemExit("The ROM does not cover National numbers: %s" % missing[:12])

    rows = []
    for nat in range(1, 387):
        o = stats_at + species_of[nat]*28
        hp, atk, dfn, spe, spa, spd = rom[o], rom[o+1], rom[o+2], rom[o+3], rom[o+4], rom[o+5]
        t1, t2 = rom[o+6], rom[o+7]
        if t1 >= len(TYPES) or t2 >= len(TYPES):
            raise SystemExit("National %d has an unknown type id" % nat)
        rows.append((hp, atk, dfn, spa, spd, spe, t1, t2))

    for nat, (name, total) in STAT_CHECKS.items():
        got = sum(rows[nat-1][:6])
        if got != total:
            raise SystemExit("%s (National %d) totalled %d, expected %d" % (name, nat, got, total))
    print("verified %d landmark species" % len(STAT_CHECKS))

    write_base_stats(OUTPUT, rows)
    print("wrote %s" % OUTPUT)

HEADER = """package dev.yoru.game;

/**
 * Base stats and types for the 386 species.
 *
 * Generated by tools/extract-base-stats.py from a Gen 3 Emerald ROM. Do not
 * edit by hand — regenerate instead. The ROM itself is never committed; these
 * are numbers and names, which are facts.
 */
"""

def write_base_stats(path, rows):
    lines = [HEADER,
             "public final class BaseStats {",
             "    private BaseStats() { }",
             "",
             "    public static final int COUNT = 386;",
             "",
             "    /** Type names, indexed by the type ids used below. */",
             "    public static final String[] TYPE_NAMES = {",
             "        " + ", ".join('"%s"' % t for t in TYPES),
             "    };",
             "",
             "    /**",
             "     * HP, Attack, Defense, Special Attack, Special Defense, Speed,",
             "     * then the two type ids. A single-typed species repeats its type,",
             "     * exactly as the game stores it.",
             "     *",
             "     * Indexed by National Dex number minus one.",
             "     */",
             "    public static final short[][] BASE = {"]
    for r in rows:
        lines.append("        {%s}," % ",".join("%d" % v for v in r))
    lines += ["    };", "",
              "    public static short[] of(int nationalDexNumber) {",
              "        if (nationalDexNumber < 1 || nationalDexNumber > COUNT)",
              "            throw new IllegalArgumentException(\"No species \" + nationalDexNumber + \".\");",
              "        return BASE[nationalDexNumber - 1];",
              "    }",
              "    public static int hp(int n) { return of(n)[0]; }",
              "    public static int attack(int n) { return of(n)[1]; }",
              "    public static int defense(int n) { return of(n)[2]; }",
              "    public static int specialAttack(int n) { return of(n)[3]; }",
              "    public static int specialDefense(int n) { return of(n)[4]; }",
              "    public static int speed(int n) { return of(n)[5]; }",
              "    public static int type1(int n) { return of(n)[6]; }",
              "    public static int type2(int n) { return of(n)[7]; }",
              "    public static int total(int n) {",
              "        var s = of(n);",
              "        return s[0] + s[1] + s[2] + s[3] + s[4] + s[5];",
              "    }",
              "}", ""]
    path.write_text("\n".join(lines), encoding="utf-8")

if __name__ == "__main__":
    main()
